<?php

include "Circle.php";

class Cylinder extends Circle{
    protected $height;

    public function __construct($radius, $color,$height)
    {
        parent::__construct($radius, $color);
        $this->height=$height;
    }
    function cylinderVolume(){
        return parent::circleArea() * $this->height;
    }

    function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo 'Height: '.$this->height.'<br/>';
        echo 'Volume: '.$this->cylinderVolume().'<br/>';
    }

}